# Tool Creator — detect repetitive patterns → create scripts/commands
# Usage: .\tool-creator.ps1 -TemplateName <name> [-Output <path>]

param(
    [string]$TemplateName,
    [string]$Output,
    [string]$Description
)

$ErrorActionPreference = "Stop"
$SETUP_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path
$ROOT_DIR = Split-Path -Parent $SETUP_DIR

. "$SETUP_DIR\project-resolve.ps1"

$TEMPLATES_DIR = "$ROOT_DIR\templates"
New-Item -ItemType Directory -Path $TEMPLATES_DIR -Force | Out-Null

# ============================================================
# Available Templates
# ============================================================

function Show-Templates {
    Write-Host ""
    Write-Host "  Available Templates:" -ForegroundColor Cyan
    Write-Host "  script=Task     New PowerShell automation script" -ForegroundColor White
    Write-Host "  command=Task    New OpenCode command (.md)" -ForegroundColor White
    Write-Host "  hook=Task      New hook script" -ForegroundColor White
    Write-Host "  skill=Task     New ECC skill template" -ForegroundColor White
    Write-Host ""
}

# ============================================================
# Create Script
# ============================================================

function New-Script {
    param([string]$Name, [string]$OutputPath)

    $safeName = $Name -replace '[^\w\-]', '_'
    $filePath = if ($OutputPath) { "$OutputPath\$safeName.ps1" } else { "$ROOT_DIR\scripts\$safeName.ps1" }

    $template = @"
# $Name — $Description
# Generated by Tool Creator

param(
    [string]$$ProjectPath
)

`$ErrorActionPreference = "Stop"
`$SETUP_DIR = Split-Path -Parent `$MyInvocation.MyCommand.Path
`$ROOT_DIR = Split-Path -Parent `$SETUP_DIR

. "`$SETUP_DIR\project-resolve.ps1"

if (-not `$ProjectPath) {
    `$ProjectPath = Get-ActiveProject
}

Write-Host "  [$Name] Running on: `$ProjectPath" -ForegroundColor Cyan

# === Your logic here ===

Write-Host "  [$Name] Done" -ForegroundColor Green
"@

    Set-Content -Path $filePath -Value $template -Encoding UTF8
    Write-Host "  [CREATE] Script created: $filePath" -ForegroundColor Green
    return $filePath
}

# ============================================================
# Create Command
# ============================================================

function New-Command {
    param([string]$Name)

    $filePath = "$ROOT_DIR\commands\$Name.md"
    $template = @"
---
description: $Description
---

# $(($Name -replace '-', ' ') -replace '(^\w)', { $_.Value.ToUpper() })

## Instructions

```powershell
.\scripts\$Name.ps1 [-ProjectPath "C:\path"]
```

## Task

`$ARGUMENTS
"@

    Set-Content -Path $filePath -Value $template -Encoding UTF8
    Write-Host "  [CREATE] Command created: $filePath" -ForegroundColor Green
    return $filePath
}

# ============================================================
# Execute
# ============================================================

if (-not $TemplateName) {
    Show-Templates
    exit 0
}

switch -Wildcard ($TemplateName) {
    "script=*" {
        $name = $TemplateName -replace '^script=', ''
        if (-not $name) { Write-Host "Error: script name required" -ForegroundColor Red; exit 1 }
        New-Script -Name $name -OutputPath $Output
        Write-Host "  [HINT] Run: .\$name.ps1" -ForegroundColor Yellow
    }
    "command=*" {
        $name = $TemplateName -replace '^command=', ''
        if (-not $name) { Write-Host "Error: command name required" -ForegroundColor Red; exit 1 }
        New-Command -Name $name
        Write-Host "  [HINT] Register in opencode.jsonc commands section" -ForegroundColor Yellow
    }
    default {
        Write-Host "  Unknown template: $TemplateName" -ForegroundColor Red
        Show-Templates
    }
}
